# @package _group_
name: 4p_8d

width: 24
height: 26
episode_length: 1000

blue_agent_count: 2
red_agent_count: 3

reward_same_color: 4
reward_oppo_color: 0

apple_color_ratio: 0.5
apple_spawn_ratio: 0.025

patch_count: 9
patch_distance: 9
