# @package _group_
name: 4p_8d

width: 16
height: 16
episode_length: 200

blue_agent_count: 4
red_agent_count: 4

reward_same_color: 3
reward_oppo_color: 1

apple_color_ratio: 0.5
apple_spawn_ratio: 0.01

patch_count: 6
patch_distance: 7