# @package _group_
name: 4p_8d

width: 16
height: 16
episode_length: 2000

blue_agent_count: 5
red_agent_count: 5

reward_same_color: 2
reward_oppo_color: 2

apple_color_ratio: 0.5
apple_spawn_ratio: 0.1

patch_count: 4
patch_distance: 8