# @package _group_
name: default

width: 16
height: 16
episode_length: 100

blue_agent_count: 2
red_agent_count: 2

reward_same_color: 3
reward_oppo_color: 1

apple_color_ratio: 0.5
apple_spawn_ratio: 0.1

patch_count: 3
patch_distance: 5

apple_rotten_time: 30