defaults:
    - ra_agent: rule
    - ma_agent: a2ccpc
    - env: default

# Experiment Settings
experiment: vanilla
seed: 0

num_train_steps: 2.5e7
# replay_buffer_capacity: 1e6 Not use on CPC
num_seed_steps: 0

eval_frequency: 10000
num_eval_episodes: 3

ma_beam_reward: -1

device: cuda

# Logging Settings
log_frequency: 1000
log_save_tb: true
save_video: true
save_model: false

# Save Buffer
render: false
svo: '45,45,45,45'



# hydra configuration
hydra:
    run:
        dir: ./experiment/${now:%Y.%m.%d}/${now:%H%M}_${experiment}_${ma_agent.name}
