# @package _group_
name: a2c
_target_: models.A2C.CPCAgent

# Default Parameters
obs_dim: ???
action_dim: ???
device: ${device}

# Specific Parameters
batch_size: 1024
seq_len: 100
num_channel: 3
use_cpc: true



