# @package _group_
name: a2clstm
_target_: models.A2CLSTMAgent.A2CLSTMAgent

# Default Parameters
obs_dim: ???
action_dim: ???
device: ${device}

lr: 5e-4
eps: 1e-5
alpha: 0.99
max_grad_norm: 0.5
entropy_coef: 0.01
v_loss_coef: 0.5

lstm_length: 200

# Specific Parameters
batch_size: 4
seq_len: ???
num_channel: 3
use_cpc: true




