# @package _group_
name: rule
_target_: models.RuleBasedAgent.RuleBasedAgentGroup


# Default Parameters

obs_dim: ???
action_dim: ???
device: ${device}

agent_types: ???

# Specific Parameters
batch_size: 1024

